
project_id = "hntsrkacolpseqnyidis"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323


[auth]
enable_signup = true
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.invite]
subject = "You have been invited"

[auth.email.template.confirmation]
subject = "Confirm your signup"

[auth.email.template.recovery]
subject = "Reset your password"

[auth.email.template.magic_link]
subject = "Your magic link"

[auth.email.template.email_change]
subject = "Confirm your email change"
